In [1]:
import pandas as pd
import numpy as np
df = pd.read_stata('Integration.dta')
df

          id  mand  ankomstaar  alder        aarslon     aar
0        1.0   1.0      2014.0   26.0   57334.093750  2017.0
1        1.0   1.0      2014.0   27.0  153148.484375  2018.0
2        2.0   0.0      2016.0   36.0   28191.710938  2017.0
3        2.0   0.0      2016.0   37.0   33956.566406  2018.0
4        3.0   1.0      2014.0   33.0  106868.898438  2017.0
...      ...   ...         ...    ...            ...     ...
4795  2398.0   1.0      2014.0   36.0  191616.437500  2018.0
4796  2399.0   1.0      2015.0   22.0   44208.378906  2017.0
4797  2399.0   1.0      2015.0   23.0   43788.902344  2018.0
4798  2400.0   1.0      2015.0   24.0  116806.382812  2017.0
4799  2400.0   1.0      2015.0   25.0   87008.007812  2018.0

[4800 rows x 6 columns]

In [ ]:
#Descriptive analysis

df['2014'] = (df.ankomstaar == 2014.0)
df['2014'] = df['2014'].astype('int')
df['2015'] = (df.ankomstaar == 2015.0)
df['2015'] = df['2015'].astype('int')
df['2016'] = (df.ankomstaar == 2016.0)
df['2016'] = df['2016'].astype('int')

#Tabel
variables = ['aarslon', 'alder', '2014', '2015', '2016']
tabel = df.groupby(['mand', 'aar'])[variables].mean().T
tabel = tabel.round(2)
tabel

mand              0.0                         1.0
aar            2017.0        2018.0        2017.0        2018.0
aarslon  31124.437500  40045.046875  61324.046875  90906.500000
alder       28.628283     29.628283     28.670341     29.670341
2014         0.341414      0.341414      0.332808      0.332808
2015         0.335354      0.335354      0.316535      0.316535
2016         0.323232      0.323232      0.350656      0.350656